apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Vault for Local Development
namespace: vault-local

resources:
- ../../../base/vault/
- namespace.yaml

patches:
- path: statefulset-patch.yaml
- path: configmap-patch.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: local-vault
    app.kubernetes.io/version: 1.15.0
    app.kubernetes.io/component: secret-management
    app.kubernetes.io/part-of: solidity-security-platform
    app.kubernetes.io/managed-by: kustomize
    environment: local
    team: infrastructure