apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Metrics Server for Local Development
namespace: kube-system

resources:
- ../../../base/metrics-server/

patches:
- path: deployment-patch.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: metrics-server
    app.kubernetes.io/part-of: blocksecops-platform
    app.kubernetes.io/managed-by: kustomize
    environment: local
    team: infrastructure