apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: postgresql-local
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_DB
    remoteRef:
      key: secret/data/postgresql
      property: POSTGRES_DB
  - secretKey: POSTGRES_USER
    remoteRef:
      key: secret/data/postgresql
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secret/data/postgresql
      property: POSTGRES_PASSWORD
  - secretKey: POSTGRES_REPLICATION_USER
    remoteRef:
      key: secret/data/postgresql
      property: POSTGRES_REPLICATION_USER
  - secretKey: POSTGRES_REPLICATION_PASSWORD
    remoteRef:
      key: secret/data/postgresql
      property: POSTGRES_REPLICATION_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: postgresql-local
spec:
  provider:
    vault:
      server: "http://vault.vault-dev.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "postgresql-role"
          serviceAccountRef:
            name: "postgresql"