apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault-metrics
  labels:
    app.kubernetes.io/name: vault
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  endpoints:
  - port: http
    interval: 30s
    path: /v1/sys/metrics
    scheme: http
    params:
      format: ['prometheus']
  namespaceSelector:
    matchNames:
    - vault-prod