apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgresql-base

labels:
- pairs:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: base-postgresql
    app.kubernetes.io/version: "15.4"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: solidity-security-platform
    app.kubernetes.io/managed-by: kustomize

resources:
  - statefulset.yaml
  - service.yaml
  - configmap.yaml
  - pvc.yaml
  - secret.yaml
  - serviceaccount.yaml
  - rbac.yaml

images:
  - name: postgres
    newTag: "15.4-alpine"