apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgresql-staging

namespace: postgresql-staging

commonLabels:
  app.kubernetes.io/instance: staging-postgresql
  environment: staging
  team: devops

resources:
  - ../../../base/postgresql
  - namespace.yaml
  - servicemonitor.yaml

patchesStrategicMerge:
  - statefulset-patch.yaml
  - configmap-patch.yaml

patches:
  - target:
      kind: StatefulSet
      name: postgresql
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1