apiVersion: v1
kind: Namespace
metadata:
  name: postgresql-staging
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: staging-postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: solidity-security-platform
    environment: staging
    team: devops