apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgresql-production

namespace: postgresql-prod

labels:
- pairs:
    app.kubernetes.io/instance: production-postgresql
    environment: production
    team: devops

resources:
  - ../../../base/postgresql
  - namespace.yaml
  - pdb.yaml
  - backup-cronjob.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - externalsecret.yaml
  - vault-policy.yaml
  - networkpolicy.yaml

patches:
- path: statefulset-patch.yaml
- path: configmap-patch.yaml
- target:
    kind: StatefulSet
    name: postgresql
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2