apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aws-load-balancer-controller-staging

namespace: aws-load-balancer-controller-staging

labels:
- pairs:
    app.kubernetes.io/instance: staging-aws-load-balancer-controller
    environment: staging
    team: devops

resources:
  - ../../../base/aws-load-balancer-controller
  - namespace.yaml
  - clusterrolebinding.yaml
  - servicemonitor.yaml

patches:
- path: deployment-patch.yaml
- path: configmap-patch.yaml
- path: serviceaccount-patch.yaml
