apiVersion: v1
kind: Namespace
metadata:
  name: redis-local
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: infrastructure-cache
    app.kubernetes.io/part-of: blocksecops-platform
    environment: local
    team: infrastructure