apiVersion: v1
kind: Namespace
metadata:
  name: vault-staging
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: staging-vault
    app.kubernetes.io/component: secrets-management
    app.kubernetes.io/part-of: blocksecops-platform
    environment: staging
    team: devops