apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-local

resources:
- namespace.yaml
- ../../../base/grafana
- ingress.yaml
- issuer.yaml
- datasources.yaml
- dashboards-configmap.yaml
- application-overview-dashboard.yaml
- api-service-dashboard.yaml
- security-tools-dashboard.yaml
- intelligence-engine-dashboard.yaml
- database-dashboard.yaml
- infrastructure-dashboard.yaml
- rbac.yaml

patchesStrategicMerge:
- namespace-patch.yaml
- deployment-patch.yaml

commonLabels:
  environment: local
  overlay: local