apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metrics-server-pdb
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/component: metrics
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
      app.kubernetes.io/component: metrics