apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-redis-secret
  namespace: argocd-local
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: argocd-redis
    creationPolicy: Owner
  data:
  - secretKey: auth
    remoteRef:
      key: secret/data/argocd
      property: redis-password
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: argocd-local
spec:
  provider:
    vault:
      server: "http://vault.vault-local.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "argocd-role"
          serviceAccountRef:
            name: "argocd-application-controller"