apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-redis-secret
  namespace: harbor-local
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: harbor-redis-secret
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: secret/data/redis
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: harbor-local
spec:
  provider:
    vault:
      server: "http://vault.vault-dev.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "harbor-role"
          serviceAccountRef:
            name: "harbor"