apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Harbor for Local Development
namespace: harbor-local

resources:
- ../../../base/harbor/
- ingress.yaml
- certificate.yaml
- externalsecret.yaml

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: harbor-core
- target:
    kind: Deployment
    name: harbor-database
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi
- target:
    kind: Deployment
    name: harbor-registry
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi
- target:
    kind: PersistentVolumeClaim
    name: harbor-registry-pvc
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: 5Gi
- target:
    kind: Service
    name: harbor-core
  patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 30880

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: image-registry
    app.kubernetes.io/part-of: solidity-security-platform
    app.kubernetes.io/managed-by: kustomize
    environment: local
    team: infrastructure