apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: external-secrets-base

labels:
- pairs:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secrets-management
    app.kubernetes.io/part-of: kubernetes-infrastructure
    app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - webhook-deployment.yaml
  - certcontroller-deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - role.yaml
  - rolebinding.yaml
  - clustersecretstore.yaml