apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: external-secrets-staging

namespace: external-secrets-staging

labels:
- pairs:
    app.kubernetes.io/instance: staging-external-secrets
    environment: staging
    team: devops

resources:
  - ../../../base/external-secrets
  - namespace.yaml
  - clusterrolebinding.yaml
  - servicemonitor.yaml

patches:
- path: clustersecretstore-patch.yaml
- path: serviceaccount-patch.yaml
